<li><a target="_blank"
                                href="[field:arcurl/]" title="[field:title/]"> <img src="[field:picname/]" alt="[field:title/]"
                                    title="[field:title/]" /></a>
          <p> <a target="_blank" href="[field:arcurl/]"
                                        title="[field:title/]"> [field:title/]</a> <span> 产品系列：[field:typename/]</span><em></em> </p>
        </li>