<li > <img src="/skin/images/jia.png" alt="[field:title/]" title="[field:title/]"
                                        class="jia" /> <img src="[field:picname/]" alt="[field:title/]" title="[field:title/]" /> <a href="[field:arcurl/]" target="_blank" title="[field:title/]">
            <h3> [field:title/]</h3>
            <em class="btn2"> <img src="/skin/images/btn_xq.png" alt="查看详情" title="查看详情" /></em> </a></li>