<div class="case_edit3 hover2 cp[field:global name=autoindex runphp="yes"]@me=@me+1;[/field:global]"> <img src="[field:picname/]" case_edit_src3="[field:picname/]" alt="[field:title/]"
                    title="[field:title/]"/>
        <div class="wz2">
          <h3> <a href="[field:arcurl/]" target="_blank" title="[field:title/]"> [field:title/]</a></h3>
          <span><a href="[field:arcurl/]" target="_blank" title="查看详情"> <img src="/skin/images/btn2.png" alt="查看详情" title="查看详情" /></a></span> </div>
      </div>