<div class="hover" id="proindex[field:global name=autoindex runphp="yes"]@me=@me+0;[/field:global]"> <img src="[field:picname/]" alt="[field:title/]" title="[field:title/]" />
        <div class="bg"> </div>
        <div class="wz">
          <h3> <a href="[field:arcurl/]" target="_blank" title="[field:title/]">[field:title/]</a></h3>
          <span><a href="[field:arcurl/]" target="_blank" title="[field:title/]"> <img src="/skin/images/btn2.png" alt="查看详情" title="查看详情" /></a></span> </div>
      </div>