<dl class="news_dl">
          <dt><span class="dt_2"> [field:pubdate function="MyDate('Y',@me)"/]</span><span class="dt_3">[field:pubdate function="MyDate('m-d',@me)"/]</span></dt>
          <dd> <span><a class="dt_1" href="[field:arcurl/]" target="_blank" title="[field:title/]">[field:title/]</a></span>
            <p> [field:description function='cn_substr(@me,300)'/]... <a href="[field:arcurl/]" target="_blank" title="详细">[详细]</a></p>
          </dd>
          <div class="clear"> </div>
        </dl>