<dl class="dl_2">
          <dt><a class="fancybox" target='_blank' href='[field:picname/]'
                                    rel="xx" title="[field:title/]" target="_blank"> <img src="[field:picname/]" alt="[field:title/]"
                                        title="[field:title/]" /></a></dt>
          <dd> <a class="fancybox" target='_blank' href='[field:picname/]'
                                        title="[field:title/]" target="_blank"> [field:title/]</a></dd>
        </dl>