<script language="javascript" type="text/javascript">
//产品标题
var OBJ_TITLE = "[field:text/]";
//视频关键词
var VIDEO_KEY = "";
//权限ID
var AUTHORITY_ID = "";
//图片路径数组
var ARR_IMG_PATH = ["[field:imgsrc/]"];
var ColumnID=4;
var ProductID=39;
var PColumnID="1";
var ColumnName="[field:text/]";
var HitLayer="ProductHits";
var Hits=200;
var MARK = "product";
var ARR_AD_MARK = ["product_detail_1"];
var SID = "0001,0004";
var atts="";
</script>