<dl >
            <dt><a href="[field:arcurl/]" target="_blank" title="[field:title/]"> <img src="[field:picname/]" alt="[field:title/]" title="[field:title/]" /></a></dt>
            <dd>
              <h3> <a href="[field:arcurl/]" target="_blank" title="[field:title/]"> [field:title/]</a></h3>
              <p>[field:description function='cn_substr(@me,120)'/]... <a href="[field:arcurl/]" target="_blank" title="查看详情">【查看详情】</a></p>
            </dd>
          </dl>