
<field:lxr itemname="联系人" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:lxr>

<field:sj itemname="手机号码" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:sj>

<field:email itemname="邮箱" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:email>

<field:cg itemname="采购意向" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:cg>
