<div class="l2tit" style="width: 95%;"> [<a target="_blank" href="[field:typelink/]">[field:typename/]</a>] <a href="[field:arcurl/]" class="f14"> [field:title/]</a><span class="f11">[
          [field:pubdate function="MyDate('Y-m-d',@me)"/]
          ]</span></div>
        <div class="clear"> </div>
        <dl class="sear_dl">
          <dt class="dt2"><a href="[field:arcurl/]"
                                    title="[field:title/]"> <img src="[field:picname/]" title="[field:title/]"
                                        alt="[field:title/]" /></a></dt>
          <dd class="d2"> [field:description/]...<a href="[field:arcurl/]"
                                        class="cRed" title="[field:title/]">[查看]</a></dd>
          <dd> <a href="[field:arcurl/]" class="a_d" title="[field:title/]"> [field:arcurl/]</a><img src="/skin/images/x3.gif"
                                            alt="3星" class="vam" /></dd>
        </dl>