<?php
$z[0]=Array("type"," <a href=\"[field:typelink/]\" title=\"[field:typename/]\" >[field:typename/]</a>",216,327);
$z[0][4]['typeid']="2";
$z[1]=Array("type"," <a href=\"[field:typelink/]\" title=\"[field:typename/]\" >[field:typename/]</a>",335,446);
$z[1][4]['typeid']="3";
$z[2]=Array("type"," <a href=\"[field:typelink/]\" title=\"[field:typename/]\" >[field:typename/]</a>",454,565);
$z[2][4]['typeid']="1";
$z[3]=Array("type"," <a href=\"[field:typelink/]\" title=\"[field:typename/]\" >[field:typename/]</a>",573,685);
$z[3][4]['typeid']="27";
$z[4]=Array("type"," <a href=\"[field:typelink/]\" title=\"[field:typename/]\" >[field:typename/]</a>",693,805);
$z[4][4]['typeid']="18";
$z[5]=Array("type"," <a href=\"[field:typelink/]\" title=\"[field:typename/]\" >[field:typename/]</a>",813,925);
$z[5][4]['typeid']="11";
$z[6]=Array("type"," <a href=\"[field:typelink/]\" title=\"[field:typename/]\" class=\"lasta\">[field:typename/]</a>",933,1058);
$z[6][4]['typeid']="16";
$z[7]=Array("global","",1428,1454);
$z[7][4]['name']="cfg_powerby";
$z[8]=Array("global","",1519,1543);
$z[8][4]['name']="cfg_beian";
$z[9]=Array("global","",1584,1605);
$z[9][4]['name']="cfg_dh";
$z[10]=Array("global","",1638,1659);
$z[10][4]['name']="cfg_sj";
$z[11]=Array("global","",1684,1705);
$z[11][4]['name']="cfg_dz";

?>